### ISSUE TITLE
Add more instructions to train vae/classifer/gan?

### ISSUE THREAD

**Issue by dhx20150812** [guangyliu/LatentOps#3]
Hi, @guangyliu , that's really an interesting and helpful work.

Recently, I'm trying to conduct experiments on my own dataset(agnews), but I find it difficult for me to run your code. So it would be great if you can add more docs about how to train the vae/classifer/gan.

Here are something I think might be important and useful:
1. Dataset preparation, including data format and detailed hyperparameters.
2. Traing scripts. For example, I tried to train my own latent classifer using the script `code/train_classifier_latent.sh`, but I'm not sure whether it is correct. Furthermore, I cannot find any scripts to train the gan. Maybe I missed something important.

Thanks in advance! Looking forward to your reply.

**Comment by guangyliu** [comment]
Thanks for the comments. I will give more details about the training part in the next two days.

**Comment by guangyliu** [comment]
Please see the updated version in https://github.com/guangyliu/LatentOps#train-vae
