### ISSUE TITLE
How to achieve text editing?

### ISSUE THREAD

**Issue by leekum2018** [guangyliu/LatentOps#4]
Hello! Thanks for your nice job! As shown in  your paper, the performances on text editing with single or compositional attribute are quite impressive. I wonder how to achieve this purpose based on your codes and checkpoints? I cannot find any instruction on this in your repo. Looking forward to your reply!

**Comment by guangyliu** [comment]
Thanks for your comment. We haven't released the text editing code so far. However, the single-attribute text editing results are in the outputs folder. We'll update the code later.

**Comment by leekum2018** [comment]
Thanks for your prompt reply! I will keep close watch on your update and look forward to it.

Or can you give some simple instruction on how to get the transfer style experiment result as in the outputs folder?

**Comment by leekum2018** [comment]
Sorry to bother you again. But I really want to want how to get the transfer style experiment result as in the outputs folder and explore the details.

**Comment by guangyliu** [comment]
I have updated the code, please run *bash lace_transfer_yelpnew.sh* (in  LatentOps/code folder) to get the single attribute text editing results of yelp. The generated file will be in the *ckpts/large_yelp/sample/transfer_repa20_1.0.txt*. You can increase repa_num in lace_transfer_yelpnew.sh to get better results (generally, 20 and 30 are good choices).

**Comment by guangyliu** [comment]
BTW, we use nltk.tokenize.word_tokenize to tokenize the sentence for evaluating the BLEU score.

**Comment by leekum2018** [comment]
Thank you very much! And I have a further question, why don't you use Optimus and instead train a VAE from scratch?

**Comment by guangyliu** [comment]
Because Optimus has some problems (e.g., they used the old version transformers library) and performs poorly on reconstruction.
