### ISSUE TITLE
修改输出文件目录

### ISSUE THREAD

**Issue by XTOZIED** [guangyliu/LatentOps#6]
你好！我尝试修改conditional_generation.sh中输出文件的目录，但是在我的新文件夹中并没有文件输出，请问有什么可能的原因嘛？

**Comment by guangyliu** [comment]
请参考这里
https://github.com/guangyliu/LatentOps/blob/57cad1003e4aefa336ef14416bcf4a4bfb669447/code/examples/big_ae/modules/eval_sampler.py#L1490
输出路径在 _sample_batch_multiple 函数中有定义
